### ISSUE TITLE
Pictures missing from homepage on Microsoft Edge

### ISSUE THREAD

**Issue by AdamHG2411** [briant1312/ecommerce-frontend#33]
Nice work on your updates to reduce image sizes on your website. One thing I noticed - when you made the images smaller you used AVIF format which is a good way to reduce file size for browsers that support it. Unfortunately, Edge still doesn't support AVIF by default. I'd recommend having a fallback format with broader support like png or jpg.

Handy tool for checking browser compatibility: https://caniuse.com/avif

<img width="1116" alt="Screenshot 2023-09-26 at 8 08 24 AM" src="https://github.com/briant1312/ecommerce-frontend/assets/45270310/40ccf0ca-a9c0-47de-a30c-5133a4908837">

**Comment by briant1312** [comment]
fixed on commit #35
